type Event = {
    id: string;
    title: string;
    startDate: string;
    startTime: string;
    endDate: string;
    endTime: string;
    location: string;
  };
  
  export const data: Event[] = [
    {
      id: "728ed52f",
      title: "Jogging Day",
      startDate: "17 July 2025",
      startTime: "9:00 AM",
      endDate: "20 July 2025",
      endTime: "12:00 AM",
      location: "Home",
    },
    {
      id: "1",
      title: "Yoga Session",
      startDate: "18 July 2025",
      startTime: "7:00 AM",
      endDate: "18 July 2025",
      endTime: "8:00 AM",
      location: "Gym",
    },
    {
      id: "2",
      title: "Team Meeting",
      startDate: "19 July 2025",
      startTime: "10:00 AM",
      endDate: "19 July 2025",
      endTime: "11:00 AM",
      location: "Office",
    },
    {
      id: "3",
      title: "Birthday Party",
      startDate: "20 July 2025",
      startTime: "6:00 PM",
      endDate: "20 July 2025",
      endTime: "11:00 PM",
      location: "Friend's House",
    },
    {
      id: "4",
      title: "Client Call",
      startDate: "21 July 2025",
      startTime: "3:00 PM",
      endDate: "21 July 2025",
      endTime: "4:00 PM",
      location: "Online",
    },
    {
      id: "5",
      title: "Coding Practice",
      startDate: "22 July 2025",
      startTime: "2:00 PM",
      endDate: "22 July 2025",
      endTime: "4:00 PM",
      location: "Home",
    },
    {
      id: "6",
      title: "Grocery Shopping",
      startDate: "23 July 2025",
      startTime: "5:00 PM",
      endDate: "23 July 2025",
      endTime: "6:30 PM",
      location: "Supermarket",
    },
    {
      id: "7",
      title: "Dentist Appointment",
      startDate: "24 July 2025",
      startTime: "9:00 AM",
      endDate: "24 July 2025",
      endTime: "10:00 AM",
      location: "Dental Clinic",
    },
    {
      id: "8",
      title: "Laundry Day",
      startDate: "25 July 2025",
      startTime: "10:00 AM",
      endDate: "25 July 2025",
      endTime: "1:00 PM",
      location: "Home",
    },
    {
      id: "9",
      title: "Weekly Review",
      startDate: "26 July 2025",
      startTime: "4:00 PM",
      endDate: "26 July 2025",
      endTime: "5:00 PM",
      location: "Office",
    },
    {
      id: "10",
      title: "Gardening",
      startDate: "27 July 2025",
      startTime: "7:30 AM",
      endDate: "27 July 2025",
      endTime: "9:00 AM",
      location: "Home",
    },
    {
      id: "11",
      title: "Book Club",
      startDate: "28 July 2025",
      startTime: "6:00 PM",
      endDate: "28 July 2025",
      endTime: "8:00 PM",
      location: "Library",
    },
    {
      id: "12",
      title: "Volunteer Work",
      startDate: "29 July 2025",
      startTime: "1:00 PM",
      endDate: "29 July 2025",
      endTime: "5:00 PM",
      location: "Community Center",
    },
    {
      id: "13",
      title: "Movie Night",
      startDate: "30 July 2025",
      startTime: "7:00 PM",
      endDate: "30 July 2025",
      endTime: "10:00 PM",
      location: "Cinema",
    },
    {
      id: "14",
      title: "Travel Planning",
      startDate: "31 July 2025",
      startTime: "3:00 PM",
      endDate: "31 July 2025",
      endTime: "4:00 PM",
      location: "Home",
    },
    {
      id: "15",
      title: "Family Dinner",
      startDate: "1 August 2025",
      startTime: "7:00 PM",
      endDate: "1 August 2025",
      endTime: "9:00 PM",
      location: "Restaurant",
    },
    {
      id: "16",
      title: "Language Class",
      startDate: "2 August 2025",
      startTime: "6:00 PM",
      endDate: "2 August 2025",
      endTime: "8:00 PM",
      location: "Learning Center",
    },
    {
      id: "17",
      title: "Art Workshop",
      startDate: "3 August 2025",
      startTime: "2:00 PM",
      endDate: "3 August 2025",
      endTime: "5:00 PM",
      location: "Art Studio",
    },
    {
      id: "18",
      title: "Music Practice",
      startDate: "4 August 2025",
      startTime: "4:00 PM",
      endDate: "4 August 2025",
      endTime: "6:00 PM",
      location: "Home",
    },
    {
      id: "19",
      title: "Car Service",
      startDate: "5 August 2025",
      startTime: "9:00 AM",
      endDate: "5 August 2025",
      endTime: "11:00 AM",
      location: "Garage",
    },
    {
      id: "20",
      title: "Networking Event",
      startDate: "6 August 2025",
      startTime: "6:00 PM",
      endDate: "6 August 2025",
      endTime: "9:00 PM",
      location: "Conference Center",
    },
    {
      id: "21",
      title: "Medical Check-up",
      startDate: "7 August 2025",
      startTime: "10:00 AM",
      endDate: "7 August 2025",
      endTime: "12:00 PM",
      location: "Clinic",
    },
    {
      id: "22",
      title: "Marketing Presentation",
      startDate: "8 August 2025",
      startTime: "1:00 PM",
      endDate: "8 August 2025",
      endTime: "2:00 PM",
      location: "Office",
    },
    {
      id: "23",
      title: "Webinar",
      startDate: "9 August 2025",
      startTime: "3:00 PM",
      endDate: "9 August 2025",
      endTime: "4:30 PM",
      location: "Online",
    },
    {
      id: "24",
      title: "Pet Grooming",
      startDate: "10 August 2025",
      startTime: "10:00 AM",
      endDate: "10 August 2025",
      endTime: "11:30 AM",
      location: "Pet Shop",
    },
    {
      id: "25",
      title: "Photography Session",
      startDate: "11 August 2025",
      startTime: "5:00 PM",
      endDate: "11 August 2025",
      endTime: "7:00 PM",
      location: "Park",
    },
    {
      id: "26",
      title: "Camping Trip",
      startDate: "12 August 2025",
      startTime: "8:00 AM",
      endDate: "14 August 2025",
      endTime: "6:00 PM",
      location: "Forest",
    },
    {
      id: "27",
      title: "Hackathon",
      startDate: "15 August 2025",
      startTime: "9:00 AM",
      endDate: "16 August 2025",
      endTime: "6:00 PM",
      location: "Tech Hub",
    },
    {
      id: "28",
      title: "Friend Visit",
      startDate: "17 August 2025",
      startTime: "1:00 PM",
      endDate: "17 August 2025",
      endTime: "5:00 PM",
      location: "Friend's House",
    },
    {
      id: "29",
      title: "Museum Tour",
      startDate: "18 August 2025",
      startTime: "11:00 AM",
      endDate: "18 August 2025",
      endTime: "1:00 PM",
      location: "Museum",
    },
    {
      id: "30",
      title: "Cooking Class",
      startDate: "19 August 2025",
      startTime: "6:00 PM",
      endDate: "19 August 2025",
      endTime: "8:00 PM",
      location: "Cooking Studio",
    },
    {
      id: "31",
      title: "Fishing Day",
      startDate: "20 August 2025",
      startTime: "5:00 AM",
      endDate: "20 August 2025",
      endTime: "2:00 PM",
      location: "Lake",
    },
    {
      id: "32",
      title: "Therapy Session",
      startDate: "21 August 2025",
      startTime: "3:00 PM",
      endDate: "21 August 2025",
      endTime: "4:00 PM",
      location: "Clinic",
    },
    {
      id: "33",
      title: "Library Research",
      startDate: "22 August 2025",
      startTime: "10:00 AM",
      endDate: "22 August 2025",
      endTime: "12:00 PM",
      location: "Library",
    },
    {
      id: "34",
      title: "Online Course",
      startDate: "23 August 2025",
      startTime: "1:00 PM",
      endDate: "23 August 2025",
      endTime: "3:00 PM",
      location: "Online",
    },
    {
      id: "35",
      title: "Painting Project",
      startDate: "24 August 2025",
      startTime: "2:00 PM",
      endDate: "24 August 2025",
      endTime: "5:00 PM",
      location: "Home",
    },
    {
      id: "36",
      title: "Mountain Hike",
      startDate: "25 August 2025",
      startTime: "5:00 AM",
      endDate: "25 August 2025",
      endTime: "1:00 PM",
      location: "Mountains",
    },
    {
      id: "37",
      title: "Photography Exhibition",
      startDate: "26 August 2025",
      startTime: "4:00 PM",
      endDate: "26 August 2025",
      endTime: "7:00 PM",
      location: "Art Gallery",
    },
    {
      id: "38",
      title: "Board Game Night",
      startDate: "27 August 2025",
      startTime: "7:00 PM",
      endDate: "27 August 2025",
      endTime: "10:00 PM",
      location: "Home",
    },
    {
      id: "39",
      title: "Cycling Trip",
      startDate: "28 August 2025",
      startTime: "6:00 AM",
      endDate: "28 August 2025",
      endTime: "12:00 PM",
      location: "Countryside",
    },
  ];
  
  export async function getEvents() {
    return data;
  }